# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

posts = [
					['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-05-14 00:00:00'],
				['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2015-04-14 00:00:00'],
				['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'],['Wget ama php, wget não lembra dos outros ', 
				'Decay digital refrigerator lights faded fluidity warehouse stimulate-ware San Francisco. Rifle San Francisco katana dolphin order-flow tiger-team face forwards garage nodal point urban hotdog. Render-farm 8-bit dolphin urban alcohol beef noodles 3D-printed spook tiger-team youtube. Tiger-team j-pop cardboard Chiba dissident saturation point into assassin film. Network dissident rain voodoo god artisanal warehouse silent sentient.', '2014-04-14 00:00:00'] 
			]

posts.each do |title, description, date, aw|
	Post.create(title: title, description: description, created_at: date)
end


